create table post (
                      id int PRIMARY KEY generated by default as identity,
                      title varchar(255) not null,
                      textpost text not null,
                      datecreate timestamp not null,
                      author varchar(255) not null,
                    im BYTEA
);


