-- drop table image_model;
-- create table image_model (
--                       id int PRIMARY KEY generated by default as identity,
--                       name varchar(100) not null,
--                       userId int not null,
--                       postId int not null,
--                       image_bytes bigint
-- );


